language: node_js

services:
  - xvfb

node_js:
  - 12.1.0

os:
  - linux
  - osx

osx_image: xcode11

before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt update
      sudo apt install -y rpm
      sudo snap install snapcraft --classic  
    fi

script:
  - npm run lint
  - npm run test
  - npm run test:e2e
  - npm run build

notifications:
  email: false
