image: Visual Studio 2017

os: unstable

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - npm install

build_script:
  - npm run lint
  - npm run test
  - npm run test:e2e
  - npm run build

test: off
